### ISSUE TITLE
Create functionality for applying filters in queryBuilder construction

### ISSUE THREAD

**Issue by carolferreguete** [conceptho/adonis-service-layer#42]
summary: Considerando o fato de que iremos precisar de funcionalidades para facilitar a realização de buscas e aplicação de filtros dentro de nossos projetos estarei propondo uma solução por meio de um query scope ( uma função que poderá ser utilizada pelo query builder )

**Comment by savioserra** [comment]
Finalizado em #41 . Fechando.
